CREATE TABLE [dbo].[User_]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Pseudo] VARCHAR(50) UNIQUE NOT NULL,
	[Email] VARCHAR(100) NOT NULL,
	[Password] VARBINARY(64) NOT NULL,
	[Salt] VARCHAR(50) NOT NULL,
	CONSTRAINT CK_Email CHECK (Email LIKE '%@%.%')
)
